Repository prgrms-web-devcourse/Team_KPPL_STUTI_BE, pull requests merged in 2022-08, with the labels that each got.

#19 [FEAT] 스터디 생성 기능을 구현하라
  src/main/docs/index.adoc
  src/main/docs/study-group.adoc
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupMapper.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/dto/StudyGroupCreateRequest.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/dto/validator/CustomDateTimeFormat.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/dto/validator/DescriptionLength.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/dto/validator/TitleLength.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/PreferredMbti.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/Region.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/StudyGroup.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/StudyMember.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/StudyMemberRole.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/StudyPeriod.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/Topic.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/PreferredMbtiRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/QuestionRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/StudyMemberRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupService.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/dto/StudyGroupCreateDto.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/dto/StudyGroupIdResponse.java
  src/main/java/prgrms/project/stuti/global/error/GlobalExceptionHandler.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/FileException.java
  src/main/java/prgrms/project/stuti/global/error/exception/InputValueException.java
  src/main/java/prgrms/project/stuti/global/error/exception/MemberException.java
  src/main/java/prgrms/project/stuti/global/error/exception/NotFoundException.java
  src/main/java/prgrms/project/stuti/global/error/exception/StudyGroupException.java
  src/main/java/prgrms/project/stuti/global/uploader/LocalImageUploader.java
  src/main/java/prgrms/project/stuti/global/uploader/common/ImageFileUtils.java
  src/main/java/prgrms/project/stuti/global/uploader/common/ImageFileValidator.java
  src/main/resources/logback-spring.xml
  src/test/java/prgrms/project/stuti/config/ServiceTestConfig.java
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/model/StudyPeriodTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupServiceTest.java
Labels: REVIEW REQUEST, FEATURE, REFACTOR, DOCUMENTATION

#21 [FEAT] 스터디 그룹 업데이트 기능을 구현하라
  src/main/docs/study-group.adoc
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupMapper.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/dto/StudyGroupUpdateRequest.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/StudyGroup.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/StudyMemberRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyMemberRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyMemberRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/StudyMemberRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupService.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/dto/StudyGroupUpdateDto.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/StudyGroupException.java
  src/test/java/prgrms/project/stuti/config/RepositoryTestConfig.java
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/studymember/StudyMemberRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupServiceTest.java
Labels: REVIEW REQUEST, FEATURE, REFACTOR, TEST, DOCUMENTATION

#30 [FEATURE] 스터디 그룹 상세조회 기능을 구현하라
  src/main/docs/study-group.adoc
  src/main/java/prgrms/project/stuti/domain/member/model/Career.java
  src/main/java/prgrms/project/stuti/domain/member/model/Field.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupMapper.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/CommonStudyGroupBooleanExpression.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyMemberRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/dto/StudyGroupApplyDto.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/dto/StudyGroupDeleteDto.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/dto/StudyGroupDetailDto.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/dto/StudyGroupIdResponse.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/response/LeaderResponse.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/response/StudyGroupDetailResponse.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/response/StudyGroupIdResponse.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/studygroup/StudyGroupConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/studygroup/StudyGroupService.java
  src/main/java/prgrms/project/stuti/global/config/JsonDateTimeFormatConfig.java
  src/test/java/prgrms/project/stuti/config/RepositoryTestConfig.java
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/StudyGroupRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/studymember/StudyMemberRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupServiceTest.java
Labels: REVIEW REQUEST, FEATURE, REFACTOR, TEST, DOCUMENTATION

#32 [FEATURE] 스터디 멤버 관리기능을 구현하라(스터디 신청 가입수락, 스터디 멤버 삭제)
  src/main/docs/study-member.adoc
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyMemberRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/StudyMember.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/CommonStudyGroupBooleanExpression.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyMemberRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyMemberRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/response/StudyMemberIdResponse.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/studygroup/StudyGroupService.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/studymember/StudyMemberConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/studymember/StudyMemberService.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/StudyGroupException.java
  src/test/java/prgrms/project/stuti/config/RepositoryTestConfig.java
  src/test/java/prgrms/project/stuti/config/ServiceTestConfig.java
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/CommonStudyGroupTestUtils.java
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/StudyMemberRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/studymember/StudyMemberRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/studygroup/StudyGroupServiceTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/studymember/StudyMemberServiceTest.java
Labels: REVIEW REQUEST, FEATURE, REFACTOR, TEST, CHORE, DOCUMENTATION

#34 [FEAT] 댓글 생성 기능을 구현하라
  src/main/java/prgrms/project/stuti/domain/feed/controller/CommentController.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/CommentMapper.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/dto/CommentRequest.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/CommentRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/service/CommentConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/CommentService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/CommentCreateDto.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/CommentResponse.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/CommentException.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/CommentControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/CommentServiceTest.java
Labels: REVIEW REQUEST, FEATURE

#52 [FEAT] 좋아요 등록, 취소(삭제) 기능을 구현하라
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostLikeController.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostLikeRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostLikeConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostLikeService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostLikeIdResponse.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/FeedException.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostLikeControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostLikeServiceTest.java
Labels: REVIEW REQUEST, FEATURE

#59 [FEAT] 토큰 관리를 쿠키에서 프론트보관으로 수정하라
  build.gradle
  src/main/java/prgrms/project/stuti/domain/member/controller/AuthenticationController.java
  src/main/java/prgrms/project/stuti/domain/member/controller/MemberController.java
  src/main/java/prgrms/project/stuti/domain/member/controller/dto/MemberIdRequest.java
  src/main/java/prgrms/project/stuti/domain/member/controller/dto/MemberSaveRequest.java
  src/main/java/prgrms/project/stuti/domain/member/controller/dto/MemberSignupResponse.java
  src/main/java/prgrms/project/stuti/domain/member/model/Member.java
  src/main/java/prgrms/project/stuti/domain/member/repository/CustomMemberRepository.java
  src/main/java/prgrms/project/stuti/domain/member/service/AuthenticationService.java
  src/main/java/prgrms/project/stuti/domain/member/service/MemberService.java
  src/main/java/prgrms/project/stuti/global/config/WebMvcConfig.java
  src/main/java/prgrms/project/stuti/global/error/ErrorResponseMapper.java
  src/main/java/prgrms/project/stuti/global/error/GlobalExceptionHandler.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/dto/TokenExpirationResponse.java
  src/main/java/prgrms/project/stuti/global/error/exception/MemberException.java
  src/main/java/prgrms/project/stuti/global/error/exception/TokenException.java
  src/main/java/prgrms/project/stuti/global/security/JwtAuthenticationFilter.java
  src/main/java/prgrms/project/stuti/global/security/OAuth2SuccessHandler.java
  src/main/java/prgrms/project/stuti/global/security/WebSecurityConfig.java
  src/main/java/prgrms/project/stuti/global/token/TokenService.java
  src/test/java/prgrms/project/stuti/domain/member/controller/AuthenticationControllerTest.java
  src/test/java/prgrms/project/stuti/domain/member/service/AuthenticationServiceTest.java
  src/test/java/prgrms/project/stuti/domain/member/service/MemberServiceTest.java
Labels: REVIEW REQUEST, FEATURE, TEST

#60 [REFACTOR] 게시글 조회 response를 변경하라
  src/main/java/prgrms/project/stuti/domain/feed/repository/FeedCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostDto.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/FeedControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/FeedServiceTest.java
Labels: REFACTOR

#65 [REFACTOR] 더미 데이터 썸네일 필드 수정, 데이터 추가, 클라이언트 에러 코드를 통일하라
  build.gradle
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/FileException.java
  src/main/java/prgrms/project/stuti/global/uploader/AwsS3ImageUploader.java
  src/main/java/prgrms/project/stuti/global/uploader/ImageUploader.java
  src/main/java/prgrms/project/stuti/global/uploader/LocalImageUploader.java
  src/main/java/prgrms/project/stuti/global/uploader/common/ImageFileUtils.java
  src/main/resources/sql/study_group.sql
  src/main/resources/sql/study_group_member.sql
  src/main/resources/sql/study_group_question.sql
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/StudyGroupMemberRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/StudyGroupRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupMemberServiceTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupQuestionServiceTest.java
  src/test/java/prgrms/project/stuti/global/uploader/ImageUploaderTest.java
Labels: REFACTOR, DOCUMENTATION

#67 [REFACTOR] 스터디 생성 지역 정보 필드의 NotNull 벨리데이션을 제거하라
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/dto/StudyGroupRequest.java
  src/main/resources/sql/study_group.sql
  src/main/resources/sql/study_group_member.sql
Labels: REFACTOR

#68 [REFACTOR] Post Response dto를 수정하라
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostDto.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostControllerTest.java
Labels: REFACTOR

#69 [REFACTOR] 스터디 그룹 문의댓글 정렬 상태 변경, 메인 과 마이 페이지 스터디 리스트 쿼리 분리, PATCH -> POST 메소드 변경하라
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupMapper.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/StudyGroup.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/CommonStudyGroupBooleanExpression.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studyquestion/CustomStudyGroupQuestionRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupMemberConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupMemberService.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupQuestionConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupService.java
  src/main/resources/sql/study_group.sql
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/StudyGroupRepositoryTest.java
Labels: FEATURE, REFACTOR

#72 [FIX, REFACTOR] 이미지 url 공백 중복을 허용하고, 게시글 수정을 POST method방식으로 변경하라
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostCommentController.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostController.java
  src/main/java/prgrms/project/stuti/domain/feed/model/PostImage.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostLikeRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostService.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostCommentControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostServiceTest.java
Labels: REFACTOR, FIX

#73 [FIX] 댓글 haxNext 조회 조건을 수정하라
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCommentCustomRepositoryImpl.java
Labels: FIX

#74 [REFACTOR] 게시글 response dto를 변경하고, 나의게시글 조회 url을 변경하라
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostController.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCommentCustomRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCommentCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCustomRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostDto.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostListResponse.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostResponse.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostServiceTest.java
Labels: REFACTOR, FIX

#75 [REFACTOR] 멤버 아이디가 4인 스터디 그룹 더미 데이터 추가, 멤버 스터디 그룹 조회 api 변경, 선호 mbti 테이블로 변경하라
  src/main/docs/study-group.adoc
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/PreferredMbti.java
  src/main/java/prgrms/project/stuti/domain/studygroup/model/StudyGroup.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/StudyGroupQueryDto.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupQuestionConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupService.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/response/StudyGroupDetailResponse.java
  src/main/java/prgrms/project/stuti/global/error/exception/StudyGroupException.java
  src/main/resources/sql/study_group.sql
  src/main/resources/sql/study_group_member.sql
  src/main/resources/sql/study_group_question.sql
  src/test/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/StudyGroupMemberRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/StudyGroupRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupMemberServiceTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupQuestionServiceTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupServiceTest.java
Labels: REFACTOR, TEST

#76 feat: github OAuth 로그인을 구현하라
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/MemberException.java
  src/main/java/prgrms/project/stuti/global/security/OAuth2Attribute.java
Labels: FEATURE

#79 [REFACTOR] 게시글 수정시 response dto 값을 수정하라
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostCommentController.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostCommentMapper.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostController.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCommentCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCommentRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostCommentConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostCommentService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostLikeService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostIdResponse.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostCommentControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostCommentServiceTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostLikeServiceTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostServiceTest.java
Labels: REFACTOR

#81 [DOCS] 적용될 sql문을 등록하라
  src/main/resources/db/migration/R__009_POST.sql
  src/main/resources/db/migration/V2__Drop_post_image_constraint.sql
Labels: DOCUMENTATION

#84 [REFACTOR, FIX] 댓글 작성자 정보를 수정하고, 댓글 삭제시 댓글정보를 Response하라
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostCommentController.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostCommentConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostCommentService.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/PostException.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostCommentControllerTest.java
Labels: REFACTOR, FIX

#86 [FIX] 대댓글 중복 select 문제를 해결하라
  src/main/java/prgrms/project/stuti/domain/feed/model/PostComment.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCommentCustomRepositoryImpl.java
Labels: FIX

#87 [FIX] 게시글 조회시 이미지 URL을 불러오도록 수정하라
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCustomRepositoryImpl.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostServiceTest.java
Labels: FIX

#88 [FIX] 이미지가 없을경우 NPE를 방지하며 빈스트링을 보내주도록 수정하라
  src/main/java/prgrms/project/stuti/domain/feed/repository/PostCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostConverter.java
Labels: FIX

#89 [FIX] refreshtoken 토큰에러코드처리에서 발생하는 오류를 해결하라
  src/main/java/prgrms/project/stuti/global/security/JwtAuthenticationFilter.java
Labels: FIX

#90 [FIX] refreshtoken 유효성검사 실패시 T002 에러를 발생시켜라
  src/main/java/prgrms/project/stuti/global/security/JwtAuthenticationFilter.java
Labels: FIX

#91 [REFACTOR] 레포지토리, 서비스 메소드 네이밍 수정, 스터디 그룹 멤버수 관련 테스트코드를 작성하라
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupQuestionRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/CommonStudyGroupBooleanExpression.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/dto/StudyGroupQueryDto.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyGroupMemberRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyGroupMemberRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studyquestion/CustomStudyGroupQuestionRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studyquestion/StudyGroupQuestionRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupMemberConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupMemberService.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupQuestionConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupQuestionService.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupService.java
  src/main/java/prgrms/project/stuti/global/uploader/common/ImageDirectory.java
  src/test/java/prgrms/project/stuti/domain/studygroup/model/StudyGroupTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/StudyGroupRepositoryTest.java
Labels: REVIEW REQUEST, REFACTOR, TEST

#93 [REFACTOR, STYLE] 패키지 구조를 수정하고, 사용하지 않는 클래스를 제거하라
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostCommentController.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostCommentMapper.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostController.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostLikeController.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/post/PostCustomRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/post/PostCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/post/PostRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/postcomment/PostCommentCustomRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/postcomment/PostCommentCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/postcomment/PostCommentRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostCommentConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostCommentService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostLikeConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostLikeService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostLikeIdResponse.java
  src/main/java/prgrms/project/stuti/domain/feed/service/response/PostCommentContentsResponse.java
  src/main/java/prgrms/project/stuti/domain/feed/service/response/PostCommentResponse.java
  src/main/java/prgrms/project/stuti/domain/feed/service/response/PostLikeIdResponse.java
  src/main/java/prgrms/project/stuti/domain/feed/service/response/PostListResponse.java
  src/main/java/prgrms/project/stuti/domain/feed/service/response/PostResponse.java
  src/main/java/prgrms/project/stuti/global/error/GlobalExceptionHandler.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/page/offset/PageResponse.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostCommentControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostLikeControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostCommentServiceTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostLikeServiceTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostServiceTest.java
Labels: REFACTOR

#97 [FIX] filter 에서 토큰 만료 에러를 발생시켜라
  src/main/java/prgrms/project/stuti/domain/member/controller/AuthenticationController.java
  src/main/java/prgrms/project/stuti/global/error/dto/TokenExpirationResponse.java
  src/main/java/prgrms/project/stuti/global/security/JwtAuthenticationFilter.java
  src/main/java/prgrms/project/stuti/global/security/OAuth2SuccessHandler.java
  src/main/java/prgrms/project/stuti/global/security/WebSecurityConfig.java
  src/main/resources/application-prod.yml
Labels: REVIEW REQUEST, FIX

#98 [FIX] naver OAuth 코드를 제거하라
  src/main/java/prgrms/project/stuti/global/security/OAuth2Attribute.java
Labels: FIX

#99 [FIX] Github 로그인오류를 해결하라
  src/main/java/prgrms/project/stuti/global/security/OAuth2SuccessHandler.java
  src/main/java/prgrms/project/stuti/global/security/WebSecurityConfig.java
Labels: FIX

#96 [REFACTOR] Dto명을 변경하고 Exception관련 컨벤션을 통일하라
  src/main/docs/index.adoc
  src/main/docs/post-comment.adoc
  src/main/docs/post-like.adoc
  src/main/docs/post.adoc
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostCommentController.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostCommentMapper.java
  src/main/java/prgrms/project/stuti/domain/feed/controller/PostController.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/postcomment/PostCommentCustomRepository.java
  src/main/java/prgrms/project/stuti/domain/feed/repository/postcomment/PostCommentCustomRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostCommentConverter.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostCommentService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostLikeService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/PostService.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostCommentChangeDto.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostCommentChild.java
  src/main/java/prgrms/project/stuti/domain/feed/service/dto/PostCommentParent.java
  src/main/java/prgrms/project/stuti/global/error/dto/ErrorCode.java
  src/main/java/prgrms/project/stuti/global/error/exception/CommentException.java
  src/main/java/prgrms/project/stuti/global/error/exception/PostException.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostCommentControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/controller/PostLikeControllerTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostCommentServiceTest.java
  src/test/java/prgrms/project/stuti/domain/feed/service/PostServiceTest.java
Labels: REFACTOR

#102 [DOCS] API Docs를 html로 만들어 배포하라
  src/main/resources/static/stuti-api.html
Labels: DOCUMENTATION

#105 [REFACTOR] 컨벤션을 통일하라
  src/main/java/prgrms/project/stuti/domain/member/controller/AuthenticationRestController.java
  src/main/java/prgrms/project/stuti/domain/member/controller/MemberMapper.java
  src/main/java/prgrms/project/stuti/domain/member/controller/MemberRestController.java
  src/main/java/prgrms/project/stuti/domain/member/controller/dto/MemberUpdateRequest.java
  src/main/java/prgrms/project/stuti/domain/member/service/AuthenticationService.java
  src/main/java/prgrms/project/stuti/global/config/JpaAuditConfig.java
  src/main/java/prgrms/project/stuti/global/error/GlobalExceptionHandler.java
  src/main/java/prgrms/project/stuti/global/error/exception/TokenException.java
  src/main/java/prgrms/project/stuti/global/security/JwtAuthenticationFilter.java
  src/main/java/prgrms/project/stuti/global/security/OAuth2SuccessHandler.java
  src/main/java/prgrms/project/stuti/global/security/WebSecurityConfig.java
  src/main/java/prgrms/project/stuti/global/security/cache/model/BlackListToken.java
  src/main/java/prgrms/project/stuti/global/security/cache/model/RefreshToken.java
  src/main/java/prgrms/project/stuti/global/security/cache/model/TemporaryMember.java
  src/main/java/prgrms/project/stuti/global/security/token/TokenService.java
  src/main/resources/application.yml
  src/test/java/prgrms/project/stuti/domain/member/controller/AuthenticationRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/member/controller/MemberRestControllerTest.java
  src/test/java/prgrms/project/stuti/domain/member/service/AuthenticationServiceTest.java
  src/test/java/prgrms/project/stuti/domain/member/service/MemberServiceTest.java
Labels: REFACTOR

#106 [REFACTOR] 스터디 그룹 전체조회 메소드 실행시간 측정, 사용하지 않는 컬럼조회를 제거하여 쿼리성능 개선, 엔티티별로 QueryDto 를 분리하라
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupQuestionRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/controller/StudyGroupRestController.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/dto/StudyGroupMemberQueryDto.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/dto/StudyGroupQueryDto.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/CustomStudyGroupRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyGroupMemberRepository.java
  src/main/java/prgrms/project/stuti/domain/studygroup/repository/studymember/CustomStudyGroupMemberRepositoryImpl.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupMemberConverter.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupMemberService.java
  src/main/java/prgrms/project/stuti/domain/studygroup/service/StudyGroupService.java
  src/main/java/prgrms/project/stuti/global/aop/ExecutionTimeLogger.java
  src/main/java/prgrms/project/stuti/global/aop/ExecutionTimer.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/studygroup/StudyGroupRepositoryTest.java
  src/test/java/prgrms/project/stuti/domain/studygroup/repository/studymember/StudyGroupMemberRepositoryTest.java
Labels: REVIEW REQUEST, FEATURE, REFACTOR

#108 [DOCS] API 명세를 수정하라
  src/main/java/prgrms/project/stuti/domain/feed/service/response/PostLikeIdResponse.java
  src/main/resources/static/stuti-api.html
Labels: REVIEW REQUEST, REFACTOR, DOCUMENTATION
